name: Deploy to Staging Server

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deploy message'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: S3 Secrets Sync
        id: s3-secrets-sync
        uses: tylerdgenius/s3-secrets-sync@v2
        with:
          command: pull
          environment: staging
          service_name: palanck
          service_type: api
          file_path: .env
          encryption_key: ${{ secrets.ENV_PASSPHRASE }}
          bucket_name: ${{ vars.SECTS_BUCKET_NAME }}
          region: ${{ vars.SECTS_REGION }}
          access_key_id: ${{ secrets.SECTS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.SECTS_ACCESS_KEY_SECRET }}
          endpoint_url: ${{ vars.SECTS_ENDPOINT_URL }}

      - name: Upload .env to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ${{ steps.s3-secrets-sync.outputs.env_file_path }}
          target: "/root"

      - name: Move needed files
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            BASE_DIR="/root/hexa-deploy"
            mkdir -p $BASE_DIR
            mv /root/github/workspace/docker-compose.yml $BASE_DIR/docker-compose.yml
            mv /root/github/workspace/.env $BASE_DIR/.env

            cd $BASE_DIR
            docker compose pull
            docker compose down
            docker compose up -d
            docker compose ps

            echo "Deployment completed successfully"

