name: Deploy to Staging Server

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deploy message'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    env:
      APP_PORT: ${{ vars.APP_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_HOST: ${{ vars.SERVER_HOST }}
      SERVER_USER: ${{ vars.SERVER_USER }}
      ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
      SECTS_BUCKET_NAME: ${{ vars.SECTS_BUCKET_NAME }}
      SECTS_REGION: ${{ vars.SECTS_REGION }}
      SECTS_ACCESS_KEY_ID: ${{ secrets.SECTS_ACCESS_KEY_ID }}
      SECTS_ACCESS_KEY_SECRET: ${{ secrets.SECTS_ACCESS_KEY_SECRET }}
      SECTS_ENDPOINT_URL: ${{ vars.SECTS_ENDPOINT_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: S3 Secrets Sync
        id: s3-secrets-sync
        uses: tylerdgenius/s3-secrets-sync@v2
        with:
          command: pull
          environment: staging
          service_name: hexa
          service_type: infra
          file_path: .env
          encryption_key: ${{ env.ENV_PASSPHRASE }}
          bucket_name: ${{ env.SECTS_BUCKET_NAME }}
          region: ${{ env.SECTS_REGION }}
          access_key_id: ${{ env.SECTS_ACCESS_KEY_ID }}
          secret_access_key: ${{ env.SECTS_ACCESS_KEY_SECRET }}
          endpoint_url: ${{ env.SECTS_ENDPOINT_URL }}

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: "${{ steps.s3-secrets-sync.outputs.env_file_path }},docker-compose.yml"
          target: "/root/hexa-deploy"

    #   - name: Move needed files
    #     uses: appleboy/ssh-action@v0.1.9
    #     with:
    #       host: ${{ env.SERVER_HOST }}
    #       username: ${{ env.SERVER_USER }}
    #       key: ${{ env.SSH_PRIVATE_KEY }}
    #       script: |
    #         BASE_DIR="/root/hexa-deploy"
    #         mkdir -p $BASE_DIR
    #         mv /root/github/workspace/docker-compose.yml $BASE_DIR/docker-compose.yml
    #         mv /root/.env $BASE_DIR/.env
            
    #         # Make test script executable if it exists
    #         if [ -f /root/test-redis.sh ]; then
    #           mv /root/test-redis.sh $BASE_DIR/test-redis.sh
    #           chmod +x $BASE_DIR/test-redis.sh
    #         fi

    #         cd $BASE_DIR
    #         docker compose pull
    #         docker compose down
    #         docker compose up -d
    #         docker compose ps

    #         echo "Deployment completed successfully"

